# Generated by Django 2.0.7 on 2018-07-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
